name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Ensure type safety
        run: npm run build

      - name: Run tests
        run: npm run test
